jwt:
  secret: 19950323

server:
  port: 5000
  servlet:
    encoding:
      charset: utf-8

spring:
  main:
    allow-circular-references: true
  datasource:
#    url: jdbc:mariadb://${rds.hostname}:${rds.port}/omechu
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: ${rds.username}
#    password: ${rds.password}
    url: jdbc:mariadb://omechu-mariadb.cs51wyqywmjh.ap-northeast-2.rds.amazonaws.com:3306/omechu
    driver-class-name: org.mariadb.jdbc.Driver
    username: omechu
    password: omechu123456!

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 821135995999-uuf1m7ejrnh5q3m77a9dkrh5bva599q1.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          kakao:
            client-id: 3c7e2a6cfb8ccd18568bc4e204e5d3ab
            redirect-uri: http://localhost:5000/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace